# yamllint disable
---
- project:
    merge-mode: squash-merge
    project-templates:
      - ansible-collection
    check:
      jobs:
        - tox-linters
        - tox-pep8
    gate:
      jobs:
        - tox-linters
        - tox-pep8
